# Generated by Django 5.1.1 on 2024-09-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_date', models.DateField()),
                ('car_make', models.CharField(default='Toyota', max_length=50)),
                ('car_model', models.CharField(default='Echo', max_length=50)),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible')], default='Sedan', max_length=20)),
                ('doors', models.PositiveIntegerField(default=4)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=20)),
                ('capacity', models.DecimalField(decimal_places=1, default=1.5, max_digits=3)),
                ('cylinders', models.PositiveIntegerField(default=4)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol - Unleaded ULP'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='Petrol', max_length=50)),
                ('gears', models.PositiveIntegerField(default=4)),
                ('odometer', models.PositiveIntegerField(default=234568)),
                ('car_colour', models.CharField(default='White', max_length=30)),
                ('car_registration', models.CharField(max_length=15, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('car_picture', models.ImageField(blank=True, null=True, upload_to='cars/images/')),
                ('car_price', models.DecimalField(decimal_places=2, help_text='Car price in the local currency', max_digits=10)),
                ('car_status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented'), ('rent_to_own', 'Rent to Own')], default='available', max_length=20)),
                ('car_title', models.CharField(max_length=200)),
                ('car_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_gallery',
            field=models.ManyToManyField(blank=True, related_name='car_gallery', to='cars.carimage'),
        ),
    ]
