# Generated by Django 5.1.1 on 2024-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('street_address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('licence_number', models.CharField(max_length=20)),
                ('licence_expiry_date', models.DateField()),
                ('option', models.CharField(choices=[('rent', 'Rent'), ('rent_to_own', 'Rent to Own'), ('purchase', 'Purchase')], default='rent', max_length=20)),
                ('licence_front_image', models.ImageField(blank=True, null=True, upload_to='licenses/front/')),
                ('licence_back_image', models.ImageField(blank=True, null=True, upload_to='licenses/back/')),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
