# Generated by Django 5.1.1 on 2024-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='car_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='car_make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='car_registration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='car_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='car_vin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
