# Generated by Django 5.1.1 on 2024-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_userdetail_car_color_userdetail_car_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('street_address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('licence', models.CharField(max_length=255)),
                ('licence_expiry', models.DateField()),
                ('option', models.CharField(max_length=50)),
                ('licence_front_image', models.ImageField(upload_to='licence_images/front')),
                ('licence_back_image', models.ImageField(upload_to='licence_images/back')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_booked_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
