# Generated by Django 5.1.1 on 2024-10-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_appointmentbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_registration',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible')], default='Sedan', max_length=50),
        ),
    ]
